### ISSUE TITLE
Aggiungere la possibilità di avete feedback alla pressione dei tasti

### ISSUE THREAD

**Issue by Rocco83** [BitPrepared/prbm-mobile#18]
### Steps to reproduce (Passi per riprodurre il problema)
 
1. aprire la tastier
2. scrivere qualcosa

### Expected behaviour (Comportamento aspettato)
Dovrebbe esserci la possibilità di inserire un feedback (vibrazione e/o suono)

### Actual behaviour (Comportamento attuale)
Non è possibile abilitare la funzione

### Enviroment (Ambiente su cui si e' generato il problema)
- **_Device Android**_: Samsung SM-T113
- **_Android Version**_: 4.4.4
- **_Stock or customized system**_: Stock
- **_APK version**_: 0.3

**Comment by cortinico** [comment]
Chiudo perché questa e' una funzionalità offerta dal sistema operativo
