### ISSUE TITLE
Aggiungere più foto in un elemento

### ISSUE THREAD

**Issue by Rocco83** [BitPrepared/prbm-mobile#20]
### Steps to reproduce (Passi per riprodurre il problema)
 
1. Creare un elemento
2. aggiungere 2 foto in un elemento

### Expected behaviour (Comportamento aspettato)
Attualmente la foto viene sempre sostituita

### Actual behaviour (Comportamento attuale)
Deve essere possibile inserire più elementi multimediali nello stesso elemento.

### Enviroment (Ambiente su cui si e' generato il problema)
- **_Device Android**_: Samsung SM-T113
- **_Android Version**_: 4.4.4
- **_Stock or customized system**_: Stock
- **_APK version**_: 0.3

**Comment by cortinico** [comment]
Aggiunta nella versione 1.1.0
