### ISSUE TITLE
Creare una interfaccia per cellulare

### ISSUE THREAD

**Issue by Rocco83** [BitPrepared/prbm-mobile#23]
### Steps to reproduce (Passi per riprodurre il problema)
 
1. Installare l'applicazione su un cellulare

### Expected behaviour (Comportamento aspettato)
L'applicazione non è compatibile con cellulari, solo con tablet

### Actual behaviour (Comportamento attuale)
L'applicazione deve essere compatibile con i cellulari (il più possibile)

**Comment by cortinico** [comment]
Aggiunta nella versione 1.1.0
